[dependencies.fixed2float]
path = "local_dependencies/fixed2float"

[dependencies.pyo3]
features = ["extension-module"]
optional = false
version = "0.15.1"

[lib]
crate-type = ["cdylib"]
name = "fixed2float"

[package]
authors = ["Francesco Urbani <francescourbanidue@gmail.com>"]
description = "Fixed point to floating point conversion utility"
documentation = ""
edition = "2021"
keywords = ["fixed", "float", "q-format"]
name = "py-fixed2float"
readme = "README.md"
repository = "https://github.com/urbanij/fixed2float"
version = "2.0.3"
[package.metadata.maturin]
name = "fixed2float"

[workspace]
