[tool.poetry]
name = "mmf-meta"
version = "0.1.11"
description = ""
authors = ["Викторов Андрей Германович <andvikt@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.7"
click = ">=8"
pandas = [
    {version = "^1.4", optional = true, python = "^3.8"},
    {version = ">= 0.22, < 1.4", optional = true, python = "^3.7"},
]
openpyxl = {version = ">=3", optional = true}
xlrd = {version = ">=2", optional = true}
opencv-python = {version = "^4.1", optional = true}
XlsxWriter = {version = "^3", optional = true}
PyTurboJPEG = {version = "^1.3", optional = true}


[tool.poetry.extras]
pandas = ["pandas", "all"]
openpyxl = ["pandas", "all"]
xlrd = ["pandas", "all"]
XlsxWriter = ["pandas", "all"]
PyTurboJPEG = ["image", "all"]
opencv-python = ["image", "all"]

[tool.poetry.dev-dependencies]

tox = "^3.17"


[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
mmfmeta = 'mmf_meta:cli'

[tool.poetry.urls]
homepage = 'https://github.com/mm-framework/mmf-meta'
documentation = 'https://mm-framework.github.io/docs/'